/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(system_time_diff.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ee5aecd89434c0fd40ef8daa6c12e223)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <timing_utils/system_time_diff.h>
// pydoc.h is automatically generated in the build directory
#include <system_time_diff_pydoc.h>

template <typename T>
void bind_system_time_diff_template(py::module& m, const char* classname)
{

    using system_time_diff = ::gr::timing_utils::system_time_diff<T>;


    py::class_<system_time_diff,
               gr::block,
               gr::basic_block,
               std::shared_ptr<system_time_diff>>(m, classname)
        .def(py::init(&gr::timing_utils::system_time_diff<T>::make),
             py::arg("update_time"),
             py::arg("output_diff"));
}

void bind_system_time_diff(py::module& m)
{

    bind_system_time_diff_template<unsigned char>(m, "system_time_diff_b");
    bind_system_time_diff_template<short>(m, "system_time_diff_s");
    bind_system_time_diff_template<float>(m, "system_time_diff_f");
    bind_system_time_diff_template<gr_complex>(m, "system_time_diff_c");
}
