/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(thresh_trigger_f.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(9749086d091518fa5b14c4b7e40c3c01)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <timing_utils/thresh_trigger_f.h>
// pydoc.h is automatically generated in the build directory
#include <thresh_trigger_f_pydoc.h>

void bind_thresh_trigger_f(py::module& m)
{

    using thresh_trigger_f = ::gr::timing_utils::thresh_trigger_f;


    py::class_<thresh_trigger_f,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<thresh_trigger_f>>(
        m, "thresh_trigger_f", D(thresh_trigger_f))

        .def(py::init(&thresh_trigger_f::make),
             py::arg("hi"),
             py::arg("lo"),
             py::arg("length"),
             D(thresh_trigger_f, make))


        .def("set_hi",
             &thresh_trigger_f::set_hi,
             py::arg("t"),
             D(thresh_trigger_f, set_hi))


        .def("set_lo",
             &thresh_trigger_f::set_lo,
             py::arg("t"),
             D(thresh_trigger_f, set_lo))


        .def("set_len",
             &thresh_trigger_f::set_len,
             py::arg("len"),
             D(thresh_trigger_f, set_len))

        ;
}
