/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(wall_clock_time.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(62ca21fd2aadd9f4acecebd4e4662b87)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <timing_utils/wall_clock_time.h>
// pydoc.h is automatically generated in the build directory
#include <wall_clock_time_pydoc.h>

void bind_wall_clock_time(py::module& m)
{

    using wall_clock_time = ::gr::timing_utils::wall_clock_time;


    py::class_<wall_clock_time,
               gr::block,
               gr::basic_block,
               std::shared_ptr<wall_clock_time>>(m, "wall_clock_time", D(wall_clock_time))

        .def(py::init(&wall_clock_time::make), py::arg("key"), D(wall_clock_time, make))


        ;
}
